// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umuzggyflyjjfmowedzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdXpnZ3lmbHlqamZtb3dlZHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjIyNDgsImV4cCI6MjA3MTk5ODI0OH0.Msj20Gj0vg9q_Dd-BXpS_sT1Po_ID9jKbsFp8TNkSIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});